### ISSUE TITLE
1.4.3 Gantt Chart

### ISSUE THREAD

**Issue by sandracsm** [aaronlam2000/INF2001_P6-5#12]
Medium Priority

To draft out the gantt chart with WBS number

Objective

- Assign WBS numbers to each task
- Create the gantt chart

Success Criteria

- WBS numbers should be assigned to each task
- Gantt chart should reflect the work assigned to each person and timeline accurately

Start Date: 21st September 2023
End Date: 22nd September 2023
Allocated Time: 2 days

**Comment by sandracsm** [comment]
https://docs.google.com/spreadsheets/d/1XdNSLSXIwd-H9vhLPp6zxjM_5cz5SbEDH-DNSL8yYg0/edit?usp=sharing

**Comment by aloysiustayy** [comment]
Can be done only after confirming all requirements.

**Comment by Cherlin01** [comment]
Drafted out and Finalized the Gantt Chart on Excel Sheet completed by Cherlin and Sandra.
WBS numbers have been assigned to each task.
Gantt chart reflects the work assigned to each person and timeline accurately.

Work was not committed to the repository.

Progress does not affect the deadline.

No changes to the criteria/success of the task.

Start Date: 21st September 2023
End Date: 22nd September 2023
