### ISSUE TITLE
2.4 Sequence Diagram

### ISSUE THREAD

**Issue by sandracsm** [aaronlam2000/INF2001_P6-5#13]
Medium Priority

To complete the Sequence Diagram

Objective

- [x] #77 
- [x] #78 

Success Criteria
 - Sequence Diagram must be clear and concise
 - Sequence Diagram must cover all requirements needed

Start Date: 23 October 2023
End Date: 27 October 2023
Allocated Time: 5 Days

**Comment by sandracsm** [comment]
https://lucid.app/lucidchart/af4d9ebb-eab8-4b4f-87ba-ea8b5724a723/edit?invitationId=inv_79174d44-d41d-4f95-94ba-66ec63701659

**Comment by aaronlam2000** [comment]
3 selected use cases for sequence diagrams:
UC1: Visualise Workload
UC3: Allocate Job
UC8: Indicate Job Preference

**Comment by Joo-ooo** [comment]
First draft of sequence diagram completed on 23rd October 2023.

Use Cases Chosen for Sequence Diagram:

- Visualise Employee Workload (UC1)
- Allocate Job (UC3)
- Indicate Job Preference (UC8)

![Image](https://github.com/aaronlam2000/INF2001_P6-5/assets/113295507/0565b2fb-d0ce-42fc-88f5-ae6f341d4361)

**Comment by sandracsm** [comment]
Sequence diagram for View Employee Workload (UC1) completed.
![image](https://github.com/aaronlam2000/INF2001_P6-5/assets/107634194/d926afda-73a8-4108-8275-73d9d6bee5f0)

**Comment by Cherlin01** [comment]
Sequence Diagram for Job Allocation (UC3) completed.
![Image](https://github.com/aaronlam2000/INF2001_P6-5/assets/63331977/96b0e6df-5463-449e-982e-03e12f4ee706)

Both sequence diagrams were completed as per requirements.
All objectives for each component have been met.

Work was not committed to the repository.

Progress does not affect the deadline.

No changes to the criteria/success of the task.

Start Date: 23 October 2023
End Date: 27 October 2023
