### ISSUE TITLE
Team Meeting 2

### ISSUE THREAD

**Issue by aaronlam2000** [aaronlam2000/INF2001_P6-5#14]
High Priority

Team meeting to follow up after client meeting

Objective:
- Consolidate client meeting minutes
- Finalize project scope
- Finalize product requirements (Functional/Non-Functional/UI)

Success Criteria:
Complete the following objectives stated above

Start Date: 6th September 2023
End Date: 6th September 2023
Allocated Time: 1 day

**Comment by poh-zun** [comment]
Client minutes has been consolidated
Project Scope Draft has been finalised
Requirements have not been finalised
Requirements are 80% completed, deadline will not be affected
Extra clarification from client needed to finalise the requirements

Start Date: 6th September 2023
End Date: 6th September 2023
