### ISSUE TITLE
Delegation of Tasks

### ISSUE THREAD

**Issue by Joo-ooo** [aaronlam2000/INF2001_P6-5#16]
Medium Priority

To plan out tasks for each member.

Objective

- Plan an equal share of the workload for each team member.

Success Criteria

- Every member should have an even workload.

Start Date: 4th September 2023
End Date: 4th September 2023
Allocated Time: 1 day

**Comment by poh-zun** [comment]
Joo - Use Case, Sequence, Activity, Architecture diagrams, Background Research, Presentation
Aaron - Product Overview, Specifications, Presentation
Aloysius - Gantt Chart, User Interface
Sandra - Safety & Security Requirements, Performance Requirements
Cherlin - Project Estimation & Plan
Poh Zun - Assumption & Dependencies

**Comment by poh-zun** [comment]
**Work Done**

- Workload assigned as stated in the comment above

**Success criteria met.**

Start Date: 4th September 2023
End Date: 4th September 2023
