### ISSUE TITLE
1.1.3.2 Product Functionality Requirements

### ISSUE THREAD

**Issue by Joo-ooo** [aaronlam2000/INF2001_P6-5#17]
Medium Priority

To write up M1 Report section - Product Requirements

Objective

- Write up all product requirements

Success Criteria
- The product requirements should meet the system's expectation
- Complete the following objectives stated above

Start Date: 5th September 2023
End Date: 7th September 2023
Allocated Time: 3 days

**Comment by aaronlam2000** [comment]
Completed  product requirements in M1 Report:

PF1: The product shall be a web-based application accessible through web browsers.
PF2: The product shall allow managers, assistant managers, pharmacists and branch staff to login using secure authentication.
PF3: The product shall allow managers and assistant managers to visualise workloads.
PF4: The product shall provide an intuitive user interface.
PF5: The product shall provide reliable performance.
PF6: The product shall provide analysis tools to help balance workload.
PF7: The product shall provide managers, assistant managers, pharmacists and branch staff the ability to view and modify their submitted availability.
PF8: The product shall provide managers, assistant managers, pharmacists and branch staff the ability to indicate their availability and preference.
PF9: The product shall allow managers, assistant managers to allocate branch staffs to the various branches based on their availability and preferences.
PF10: The product shall allow managers, assistant managers to visualise staff workload and view the staff with the lowest working hours and staffs who have exceeded 40 working hours.
PF11: The product shall allow branch staff and pharmacists to reject the shift allocated to them.

Work was not committed to the repository.

Progress does not affect the deadline.

No changes to the criteria/success of the task.

Start Date: 5th September 2023
End Date: 7th September 2023
