### ISSUE TITLE
1.2.1 User Interface Requirements

### ISSUE THREAD

**Issue by Joo-ooo** [aaronlam2000/INF2001_P6-5#18]
Medium Priority

To draft out user interface(UI) requirements.

Objective

- Draft out the UI requirements for the web application before meeting the client
- Find some questions for the client about UI if needed.

Success Criteria

- Drafted out at least 5 UI requirements before meeting the client.
- Done drafting by the deadline mentioned below

Start Date: 5th September 2023
End Date: 7th September 2023
Allocated Time: 3 days

**Comment by poh-zun** [comment]
**Work Done**

- Successfully drafted out 8 different categories of UI requirements with 1 - 2 descriptions each.

Work was not committed to the repository.

Progress does not affect the deadline.

No changes to the criteria/success of the task.

Start Date: 5th September 2023
End Date: 7th September 2023
