### ISSUE TITLE
1.2.4 Other Requirements: Database

### ISSUE THREAD

**Issue by Joo-ooo** [aaronlam2000/INF2001_P6-5#19]
Medium Priority

To write up M1 Report section - Database Requirements

Objective

- Draft out database requirements

Success Criteria
- The database requirements should fit the systems well.
- Met the timeline set
- Complete the objectives stated above

Start Date: 12th September 2023
End Date: 13th September 2023
Allocated Time: 2 days

**Comment by poh-zun** [comment]
**Drafted out database requirements in M1 Report as below:**

DR1: The system shall use a relational database management system (RDBMS) such as MySQL.
DR2: The system shall define the database schema with tables as follows:
User Information (user_id, name, password, role_id, email)
Product (product_id, product_name, product_category, price, stock_left)
Role Information (role_id, role_name)
Working Schedule (Date, user_id, starting_time, ending_time)
Staff Availability (user_id, date_available)
DR3: The system shall ensure data integrity by implementing referential integrity constraints and usage of primary keys, foreign keys and unique constraints.
DR4: The system shall ensure data security by encrypting sensitive data such as passwords using industry-standard encryption algorithms and implementing role-based access control.
DR5: The system shall maintain and improve the performance and scalability via optimisation of database queries for fast retrieval of information and implement indexing on frequently queried attributes.
DR6: The database shall be backed up regularly to ensure data recovery in case of system failures or data corruption.

Work was not committed to the repository.

Progress does not affect the deadline.

No changes to the criteria/success of the task.

Start Date: 12th September 2023
End Date: 13th September 2023
