### ISSUE TITLE
1.3.3 Activity Diagram

### ISSUE THREAD

**Issue by poh-zun** [aaronlam2000/INF2001_P6-5#2]
Medium Priority

To draft up Activity Diagram as part of M1 Submission.

Objectives
- Draft out activity diagram for IT Administrator
- Draft out activity diagram for Staff
- Draft out activity diagram for Manager

Success Criteria:

1.  Activity Diagram must contain alternate scenarios and error messages

Start Date: 19th September 2023
End Date: 21st September 2023
Allocated Time: 3 days

**Comment by sandracsm** [comment]
https://lucid.app/lucidchart/c9347dfa-6d9a-4cf5-821c-b886cf6c5b9e/edit?invitationId=inv_cd7c135d-f723-4674-93cd-657e1cc55a83

**Comment by Joo-ooo** [comment]
Create a draft of the Activity Diagram, will refine it after having received information from Prof on what it should cover (entire system or individual use cases)


![Image](https://github.com/aaronlam2000/INF2001_P6-5/assets/113295507/03a5aa1e-5068-43f4-8734-653ef345a362)

**Comment by poh-zun** [comment]
Help with the activity diagram for IT Admins

![Image](https://github.com/aaronlam2000/INF2001_P6-5/assets/60766107/293bc1fd-04be-4948-a400-532489e8fb6f)

**Comment by Joo-ooo** [comment]
Refinement of activity diagram for manager and staff section

![Image](https://github.com/aaronlam2000/INF2001_P6-5/assets/113295507/dd8242b0-99e9-4bc9-b458-801759a153a2)

**Comment by Joo-ooo** [comment]
Finalise design of activity diagram to include error messages as well.

![Image](https://github.com/aaronlam2000/INF2001_P6-5/assets/113295507/b93d6fa8-fd22-4d4a-9fde-d0dd91261f24)

![Image](https://github.com/aaronlam2000/INF2001_P6-5/assets/113295507/17802e37-a3ca-4b8a-a88b-56889d42582b)

Work not committed to repository.

Progress does not affect deadline.

No changes to criteria/success

Start Date: 19th September 2023
End Date: 21st September 2023
