### ISSUE TITLE
Drafting Functional Requirements

### ISSUE THREAD

**Issue by Joo-ooo** [aaronlam2000/INF2001_P6-5#21]
Medium Priority

To write up M1 Report section - Functional Requirements

Objective

- Draft out functional requirements

Success Criteria
- To draft out Functional Requirements for all roles

Start Date: 4th September 2023
End Date: 6th September 2023
Allocated Time: 2 days

**Comment by Cherlin01** [comment]
Drafted out functional requirements in M1 Report:

For Manager
FR1: The system shall provide secure user authentication using unique credentials for Managers/Admin
FR2: The system shall give managers the ability to assign roles and permissions to staff members within the system.
FR3: The system shall allow managers to visualise staff workloads using graphs and chart on their landing page
FR4: Managers shall have the ability to allocate jobs to staff members for a specific week
FR5: The manager shall have the ability to view the top 3 staff with lowest working hours on their landing page.
FR6: The system shall sort the staff by lowest work hours on the manager’s landing page

For Staffs
FR7: Staff members shall have the ability to view their weekly job assignments on their landing page
FR8: Staff members shall have the ability to view their monthly workload on their landing page
FR9: On the staff landing page, staff shall have the ability to view their weekly job assignments and overall workload for the month on their landing page.
FR10: The system shall allow staff to indicate their branch preference.
FR11: The system shall allow staff to indicate their shift hour availability.
FR12: The system shall allow staff to reject a job assignment

Start Date: 4th September 2023
End Date: 6th September 2023

**Comment by aloysiustayy** [comment]
Added Functional Requirements for IT Administrator.

Start Date: 4th September 2023
End Date: 6th September 2023

**Comment by aloysiustayy** [comment]
Successfully drafted Functional Requirements (Done by Aloysius).

Work was not committed to the repository.

Progress does not affect the deadline.

No changes to the criteria/success of the task.

Start Date: 4th September 2023
End Date: 6th September 2023
