### ISSUE TITLE
Refinement of Database Requirements

### ISSUE THREAD

**Issue by aloysiustayy** [aaronlam2000/INF2001_P6-5#32]
Medium Priority

To refine database requirements drafted on #19 .

Objective

- Refine the database requirements for the web application drafted out after the meeting with clients.
- Complete the refinement by the deadline mentioned.

Success Criteria

- Complete the following objectives stated above
- Every single requirement should be best fit for the web application

Start Date: 11th September 2023
End Date: 12th September 2023
Allocated Time: 2 days

**Comment by poh-zun** [comment]
**Work done**

- Done refinement for database requirements that suit the web application.

Work was not committed to the repository.

Progress does not affect the deadline.

No changes to the criteria/success of the task.

Start Date: 11th September 2023
End Date: 12th September 2023
