### ISSUE TITLE
Refinement of Non-Functional Requirements

### ISSUE THREAD

**Issue by aloysiustayy** [aaronlam2000/INF2001_P6-5#33]
High Priority

To further refine M1 Report section - Non-functional Requirements

Objective
- Refine Non-functional Requirements (NFR)

Success Criteria
- Team should go through all NFRs and collectively agree on it.

Start Date: 11th September 2023
End Date: 12th September 2023
Allocated Time: 2 days

**Comment by sandracsm** [comment]
Successfully refined non-functional requirements (Done by Aloysius).

Work was not committed to the repository.

Progress does not affect the deadline.

No changes to the criteria/success of the task.

Start Date: 11th September 2023
End Date: 12th September 2023
