### ISSUE TITLE
Refinement of Non-Functional Requirements for Safety and Security

### ISSUE THREAD

**Issue by aloysiustayy** [aaronlam2000/INF2001_P6-5#34]
High Priority
To further refine M1 Report section - Non-Functional Requirements for Safety and Security

Objective
- Refine Non-Functional Requirements for Safety and Security

Success Criteria
- Safety and Security Requirements should be detailed and concise

Start Date: 11th September 2023
End Date: 12th September 2023
Allocated Time: 2 days

**Comment by sandracsm** [comment]
Successfully refined Non-Functional Requirements for Safety and Security (Done by Cherlin).

Work was not committed to the repository.

Progress does not affect the deadline.

No changes to the criteria/success of the task.

Start Date: 11th September 2023
End Date: 12th September 2023
