### ISSUE TITLE
Refinement of Non-Functional Requirements for Performance

### ISSUE THREAD

**Issue by aloysiustayy** [aaronlam2000/INF2001_P6-5#35]
Medium Priority

To Refine M1 Report Section - Non-Functional Performance Requirements

Objective
- Produce more Non-Functional Requirements (NFR)
- Improved on existing NFRs using the 7 traits of good requirements

Success Criteria
- Performance Requirements should be detailed and concise

Start Date: 11th September 2023
End Date: 13th September 2023
Allocated Time: 3 days

**Comment by Joo-ooo** [comment]
Additional NFRs were identified and added to the existing list and existing NFRs were improved by implementing the 7 traits of good requirements to ensure they are verifiable, clear, concise, traceable, viable, consistent and implementation-free.

The work was not committed to the project repository.

This progress does not affect the project's deadline.

There are no changes to the success/completion criteria of this task.

Start date: 11th September 2023
End date: 13th September 2023
