### ISSUE TITLE
Refinement of Functional Requirements for Staffs

### ISSUE THREAD

**Issue by aloysiustayy** [aaronlam2000/INF2001_P6-5#36]
High Priority

To further refine M1 Report section - Functional Requirements for Staff

Objective
- Refine Functional Requirements for Staffs

Success Criteria
-  Functional Requirements for Staffs must be detailed and concise

Start Date: 11th September 2023
End Date: 12th September 2023
Allocated Time: 2 days

**Comment by sandracsm** [comment]
Successfully refined functional requirements for Managers (Done by Aaron).

Work was not committed to the repository.

Progress does not affect the deadline.

No changes to the criteria/success of the task.

Start Date: 11th September 2023
End Date: 12th September 2023
