### ISSUE TITLE
1.3.2.3 Use Case Descriptions for IT Administrator

### ISSUE THREAD

**Issue by aloysiustayy** [aaronlam2000/INF2001_P6-5#38]
High Priority

M1 Report Section - Appendix A - Use Case Descriptions (IT Administrator)

Objectives
- Write up Use Case Descriptions for IT Administrator

Success Criteria
- Use case descriptions should match use case diagram

Start Date: 19th September 2023
End Date: 20th September 2023
Allocated Time: 2 days

**Comment by Joo-ooo** [comment]
Drafted out use case descriptions for IT Administrators, seeking clarity from Prof during lab lessons.

![Image](https://github.com/aaronlam2000/INF2001_P6-5/assets/113295507/5ce82372-7003-4960-8a07-8d1a292402f0)

![Image](https://github.com/aaronlam2000/INF2001_P6-5/assets/113295507/da0dccc8-d919-43ec-a5dd-cbf9ccbbc54f)

![Image](https://github.com/aaronlam2000/INF2001_P6-5/assets/113295507/7c26791b-788f-4685-a8f3-ae47612ffcb1)

![Image](https://github.com/aaronlam2000/INF2001_P6-5/assets/113295507/72a5aa7a-df24-4b5c-8d65-9e12cb1e1b9f)

![Image](https://github.com/aaronlam2000/INF2001_P6-5/assets/113295507/54569927-3bd2-4d27-9b86-cf36fa409943)

**Comment by aloysiustayy** [comment]
IT Administrator's Use Case Descriptions updated, along with the Use Case ID after refinement of Use Case Diagrams.

- UC10: Create Employee Account
- UC11: Delete Employee Account
- UC12 Reset Employee Account Password
- UC13: Assign Role to Employee
- UC14: Edit Role Permission

Start Date: 13th September 2023
End Date: 14th September 2023

**Comment by aloysiustayy** [comment]
refined some use case descriptions

**Comment by aaronlam2000** [comment]
IT Administrator's Use Case Descriptions updated, along with the Use Case ID after refinement of Use Case Diagrams.

Completed the 5 use case description for IT Administrator
Work was not committed to the repository.

Progress does not affect the deadline.

No changes to the criteria/success of the task.

Start Date: 19th September 2023
End Date: 20th September 2023
