### ISSUE TITLE
1.3.2.1 Use Case Descriptions: Managers/ Assistant Managers

### ISSUE THREAD

**Issue by aloysiustayy** [aaronlam2000/INF2001_P6-5#39]
High Priority

To Draft M1 Report Section - Appendix A - Use Case Descriptions (Managers)

Objectives
Draft out use case descriptions for Managers

Success Criteria
- Use case descriptions should match use case diagram

Start Date: 15th September 2023
End Date: 19th September 2023
Allocated Time: 3 days

**Comment by Joo-ooo** [comment]
Drafted out use case descriptions for Managers / Assistant Managers, seeking clarity from Prof during lab lessons.

![Image](https://github.com/aaronlam2000/INF2001_P6-5/assets/60766107/68361b8c-b0ba-458c-812d-c1863c220925)

![Image](https://github.com/aaronlam2000/INF2001_P6-5/assets/60766107/7d7f1608-1a7b-4c0d-8a22-f204c2255a73)

![Image](https://github.com/aaronlam2000/INF2001_P6-5/assets/60766107/634c71ea-5af5-4979-b676-e45b97084079)

![Image](https://github.com/aaronlam2000/INF2001_P6-5/assets/60766107/ff1912a7-b37c-43c8-98a1-7086d0fc8b80)

**Comment by poh-zun** [comment]
Drafted out some other use case descriptions for Manager / Assistant Manager.

![Image](https://github.com/aaronlam2000/INF2001_P6-5/assets/60766107/6ca5b6fb-155b-48b7-8d53-754762a1c9f2)

![Image](https://github.com/aaronlam2000/INF2001_P6-5/assets/60766107/f8e1b337-b374-48fc-9ed5-703be0b01a02)

![Image](https://github.com/aaronlam2000/INF2001_P6-5/assets/60766107/9d0d7ced-b8aa-4012-a883-c07a5ba7be5f)

**Comment by poh-zun** [comment]
**Work Done**

- Completed the 7 use case description for Manager / Assistant Manager.

Work was not committed to the repository.

Progress does not affect the deadline.

No changes to the criteria/success of the task.

Start Date: 15th September 2023
End Date: 19th September 2023
