### ISSUE TITLE
Team Meeting 1

### ISSUE THREAD

**Issue by poh-zun** [aaronlam2000/INF2001_P6-5#4]
High Priority

Initial group meeting to discuss about M1 Report and client meeting.

Objective:

- Finalise questions to be asked for client meeting
- Update Kanban board with new tasks
- Draft out M1 Report section - Introduction

Success Criteria
- Complete the following objectives stated above

Start Date: 4th September 2023
End Date: 4th September 2023
Allocated Time: 1 day

**Comment by poh-zun** [comment]
Team meeting on 4th Sept 2023, Monday 8pm with all the team members.

**Comment by poh-zun** [comment]
Finalise questions for clients.

**Comment by poh-zun** [comment]
Update Kanban board

**Comment by Cherlin01** [comment]
Discuss report details

**Comment by sandracsm** [comment]
- [x] #7
- [x] Discuss report details

**Comment by poh-zun** [comment]
M1 Report Introduction has been drafted out.
Questions for client meeting has been finalised.
New tasks has been added to the project's Kanban board

Start Date: 4th September 2023 , 8:00PM
End Date: 4th September 2023 , 9:55PM
