### ISSUE TITLE
1.3.2.2 Use Case Descriptions: Staff

### ISSUE THREAD

**Issue by aloysiustayy** [aaronlam2000/INF2001_P6-5#40]
High Priority

To Draft M1 Report Section - Appendix A - Use Case Descriptions (Staff)

Objectives
Draft out use case descriptions for Staff.

Success Criteria
- Use case descriptions should match Use Case Diagram.

Start Date: 18th September 2023
End Date: 19th September 2023
Allocated time: 2 days

**Comment by Joo-ooo** [comment]
Drafted out use case descriptions for Pharmacist and Branch Staff, seeking clarity from Prof during lab lessons.

![image](https://github.com/aaronlam2000/INF2001_P6-5/assets/113295507/c90bea01-d3c5-475e-b821-a18decae7b8b)

![image](https://github.com/aaronlam2000/INF2001_P6-5/assets/113295507/ec408a01-4c9b-40bb-97a4-1c17b8797125)

![image](https://github.com/aaronlam2000/INF2001_P6-5/assets/113295507/c18dae93-847c-4a6d-bdb2-18adb189038a)

![image](https://github.com/aaronlam2000/INF2001_P6-5/assets/113295507/ef6f4cf0-bd8f-4c32-9111-a3c2c298a854)

![image](https://github.com/aaronlam2000/INF2001_P6-5/assets/113295507/59cd7ffc-7b8d-45a7-a672-e1d9097d78be)

![image](https://github.com/aaronlam2000/INF2001_P6-5/assets/113295507/e1cb417a-5112-4528-9acb-d969aebd67c8)

![image](https://github.com/aaronlam2000/INF2001_P6-5/assets/113295507/fb7f802a-0c26-4106-830d-d2616c315fa9)

![image](https://github.com/aaronlam2000/INF2001_P6-5/assets/113295507/4cab76c9-368f-4748-8502-c0b120a074c8)

**Comment by aloysiustayy** [comment]
Staff's Use Case Descriptions updated, along with the Use Case ID after refinement of Use Case Diagrams.
Completed the use case description for Staff

Work was not committed to the repository.

Progress does not affect the deadline.

No changes to the criteria/success of the task.

Start Date: 18th September 2023
End Date: 19th September 2023
