### ISSUE TITLE
2.2 Class Diagram

### ISSUE THREAD

**Issue by Cherlin01** [aaronlam2000/INF2001_P6-5#41]
Medium Priority

To complete the Class Diagram

Objective

- [x] #66
- [x] #67 
- [x] #68  

Success Criteria
 - Class Diagram must be clear and concise
 - Class Diagram must cover all requirements needed

Start Date: 25th September 2023
End Date: 20th October 2023
Allocated Time: 20 Days

**Comment by Joo-ooo** [comment]
Completed Class Diagram with all the relevant modules such as User Management, Role Permissions Management, Preferences Management, Language Management and Workload Management. Relations between classes have been defined using associations and constraints.

![Image](https://github.com/aaronlam2000/INF2001_P6-5/assets/113295507/4317f48e-a130-41a1-955e-c43edcbe2589)

**Comment by aaronlam2000** [comment]
Note: Remove module boxes for the final class diagram.

**Comment by Joo-ooo** [comment]
Addition of interfaces into the class diagram.

Interfaces added:

- iRole
- iLanguage
- iPreference
- iManageWorkload
- iViewWorkload

![Image](https://github.com/aaronlam2000/INF2001_P6-5/assets/113295507/0120a346-ee22-44fd-a83d-8d8f684e5040)

**Comment by aaronlam2000** [comment]
![Image](https://github.com/aaronlam2000/INF2001_P6-5/assets/32828969/642ecccc-fb78-4c91-9994-3e04ae69b2fe)


Full class diagram refined and completed as per requirements.
All success criteria has been met.

Work was not committed to the repository.

Progress does not affect the deadline.

No changes to the criteria/success of the task.

Start Date: 25th September 2023
End Date: 20th October 2023
