### ISSUE TITLE
2.3 Component Diagram

### ISSUE THREAD

**Issue by Cherlin01** [aaronlam2000/INF2001_P6-5#42]
Medium Priority

To complete the Component Diagram

Objective

- [x] #72 
- [x] #73 
- [x] #74 
- [x] #75 
- [x] #76 

Complete Component Diagram

Success Criteria
 - Component Diagram must be clear and concise
 - Component Diagram must cover all requirements needed

Start Date: 9th October 2023
End Date: 20th October 2023
Allocated Time: 10 Days

**Comment by aaronlam2000** [comment]
First draft of component diagram completed on 20th October 2023.

**Components and Sub-Components in the diagram** 
UserManagement: (Main)
- Administrator (Sub)
- Manager (Sub)
- Staff (Sub)

WorkloadManagement: (Main)
- ManageWorkload (Sub)
- ViewWorkload (Sub)

PreferencesManagement (Main)
RolePermissionsManagement (Main)
LanguageManagement (Main)


![Image](https://github.com/aaronlam2000/INF2001_P6-5/assets/32828969/4930fad7-c0e7-4213-8374-efb73566e105)

**Comment by aaronlam2000** [comment]
![Image](https://github.com/aaronlam2000/INF2001_P6-5/assets/32828969/7c63d7a6-6412-4573-bc62-7858fdb3fdcd)


Full component diagram completed as per requirements.
All objectives for each component has been met.

Work was not committed to the repository.

Progress does not affect the deadline.

No changes to the criteria/success of the task.

Start Date: 9th October 2023
End Date: 20th October 2023
