### ISSUE TITLE
1.2.2 Functional Requirements

### ISSUE THREAD

**Issue by Cherlin01** [aaronlam2000/INF2001_P6-5#48]
High Priority

To write up M1 Report section - Functional Requirements

Objective
- To complete Functional Requirements for Managers, Staffs, and IT Administrator

Success Criteria
- Functional Requirements for Managers must be detailed and concise
- Functional Requirements for Staffs must be detailed and concise
- Functional Requirements for IT Administrator must be detailed and concise

Start Date: 7th September 2023
End Date: 11th September 2023
Allocated Time: 3 days

**Comment by sandracsm** [comment]
Drafting and refining of all functional requirements completed by Aaron and Aloysius.
Functional Requirements for Managers, Staffs and IT Administrator are detailed and concise.
 
Work was not committed to the repository.

Progress does not affect the deadline.

No changes to the criteria/success of the task.

Start Date: 7th September 2023
End Date: 11th September 2023
