### ISSUE TITLE
1.4 Project Estimation and Plan

### ISSUE THREAD

**Issue by sandracsm** [aaronlam2000/INF2001_P6-5#53]
High priority

To Draft M1 Report Section - Project Estimation and Plan

Objectives

- Complete writing up Project Estimation and Plan which includes Size Estimation, Effort Estimation, Gantt Chart, and Software Development Life Cycle

Success Criteria

- Calculate Unadjusted Use Case Weight (UUCW) using Unadjusted Actor Weight (UAW) and Unadjusted Transaction Weight (UTW)
- Calculate Technical Complexity Factor (TCF) and Environmental Complexity Factor (ECF) to be used with UUCW to get UCP for project size estimation
- Using the minimum of 15 developer hours and maximum of 30 developers hours for each UCP to calculate the effort estimation
- Project duration is measured.

Start Date: 19th September 2023
End Date 22nd September 2023

**Comment by aloysiustayy** [comment]
Successfully drafted and complete writing Project Estimation and Plan
Number of transactions were calculated at Use Case Description section to categorise complexity.
Used UAW and UTW to get UUCW.
Used UUCW, TCF, and EF to get UCP value.
Used UCP value to estimate effort required.
Measured project duration as well.

Work was not committed to the repository.

Progress does not affect the deadline.

No changes to the criteria/success of the task.

Start Date: 19th September 2023
End Date: 22nd September 2023
