### ISSUE TITLE
1.1 Requirements Gathering

### ISSUE THREAD

**Issue by aloysiustayy** [aaronlam2000/INF2001_P6-5#57]
High Priority

To gather all requirements needed to come up with Specific Requirements Documentation later on.

Objective

Complete and draft up the following: 

1. Client Meeting,
2. Product Scope
3. Overall Description
4. Product Functionality
5. Assumptions and Dependencies

Success Criteria

1. Meet client to clarify initial requirements (functional and non-functional requirements), assumptions and dependencies
2. Team meeting and background research to draft out product scope and overall description of the product

Start Date: 4th September 2023
End Date: 7th September 2023
Allocated Time: 4 days

**Comment by Joo-ooo** [comment]
Met with the client to confirm the functional and non-functional requirements, had team meetings to draft out what the product should do and using what framework for the design of the product

Work done was not committed to repository

No changes to criteria/success

Start Date: 4th September 2023
End Date: 7th September 2023
