### ISSUE TITLE
1.4.1 Size Estimation

### ISSUE THREAD

**Issue by poh-zun** [aaronlam2000/INF2001_P6-5#58]
High Priority

To Draft M1 Report Section - Project Size Estimation and Plan (Size Estimation)

Objective

- Calculate Use Case Point

Success Criteria

- Calculate Unadjusted Use Case Weight (UUCW) using Unadjusted Actor Weight (UAW) and Unadjusted Transaction Weight (UTW)
Calculate Technical Complexity Factor (TCF) and Environmental Complexity Factor (ECF) to be used with UUCW to get UCP for project size estimation

Start Date: 19th September 2023
End Date: 21th September 2023
Allocated Time: 3 days

**Comment by aloysiustayy** [comment]
calculated number of transactions for UC9 to UC14

**Comment by aaronlam2000** [comment]
Calculated Use Case Description transactions UC1 to UC8

**Comment by aloysiustayy** [comment]
Number of transactions were calculated at Use Case Description section to categorise complexity.
Used UAW and UTW to get UUCW.
Used UUCW, TCF, and EF to get UCP value.

The work was not committed to the project repository.

This progress does not affect the project's deadline.

There are no changes to the success/completion criteria of this task.

Start Date: 11th September 2023
End Date: 13th September 2023
