### ISSUE TITLE
1.4.2 Effort Estimation

### ISSUE THREAD

**Issue by poh-zun** [aaronlam2000/INF2001_P6-5#59]
High Priority

Write up M1 Report Section - Project Estimation and Plan (Effort Estimation)

Objective

- Calculate an estimate the amount of developer hours needed for this project

Success Criteria

- Using a minimum and maximum set of developer hours for each UCP to calculate the effort estimation

Start Date: 19th September 2023
End Date: 21th September 2023
Allocated Time: 3 days

**Comment by aaronlam2000** [comment]
Used calculated Use Case Point to estimate effort.
Calculated minimum and maximum number of hours
Final Estimated Effort range resulted with 37 days to 74 days

Work was not committed to the repository.

Progress does not affect the deadline.

No changes to the criteria/success of the task.

Start Date: 19th September 2023
End Date: 21th September 2023
