### ISSUE TITLE
1.1.1 Client Meeting

### ISSUE THREAD

**Issue by aaronlam2000** [aaronlam2000/INF2001_P6-5#6]
High Priority

To meet up with client online to clarify about the product's requirements

Objective

- Ask prepared questions for the client
- Clarify with client about the product's initial requirements

Success Criteria

- Prepared questions for the client has been asked
- Initial requirements has been clarified

Start Date: 6th September 2023
End Date: 6th September 2023
Allocated Time: 1 day

**Comment by poh-zun** [comment]
Meeting done at 10.50am

**Comment by poh-zun** [comment]
Client meeting 1 minutes:
Who have access to the visualization?
Allow system admin to edit and manage access to visualizations.
Staff can only see the time slots and schedules in their level (Staff schedules)
Managers have graphs/histograms to visualise workload
Add options to filter by hours, daily, weekly, monthly, yearly etc)


What data to use to visualize workload?
Export data to view in excel sheets or other applications
Can use graphs, table, histogram to visualise workload for the manager (allow multiple ways to display)


Is there a maximum number of hours staff can work?
Work as much as they want, cap should be a variable not fixed (so can be set)

Who can add staff to system, and what information to include about the new staff?
Manager and IT staff should be able to add new staff/manager to the team
IT staff should be able to enable the job responsibilities, amendment rights, accessibility rights
Staff preference based on?
Staff preference location timeslot (work in day, evening, weekend shift, public holiday)
Lead time set as variable like 1 week or a few days

**Comment by aaronlam2000** [comment]
Doubts about the product's initial requirements has been clarified
Client meeting session have been recorded
Client meeting minutes have been consolidated

Progress does not affect the deadline.

No changes to the criteria/success of the task.

Start Date: 6th September 2023
End Date: 6th September 2023
