### ISSUE TITLE
1.2.2.3 Functional Requirements: IT Administrator

### ISSUE THREAD

**Issue by poh-zun** [aaronlam2000/INF2001_P6-5#60]
High Priority

To further refine M1 Report section - Functional Requirements for IT Administrator

Objective
- Draft and refine Functional Requirements for IT Administrator

Success Criteria
- Functional Requirements for IT Administrator must be detailed and concise.
- The requirements fit the needs of the client.

Start Date: 7th September 2023
End Date: 11th September 2023
Allocated Time: 3 days

**Comment by aaronlam2000** [comment]
Drafting and refining of all functional requirements for IT Administrator completed.
There are a total of 5 requirements for staff:  FR18 to FR22

Work was not committed to the repository.

Progress does not affect the deadline.

No changes to the criteria/success of the task.

Start Date: 7th September 2023
End Date: 11th September 2023
