### ISSUE TITLE
1.2.2.2 Functional Requirements: Staff

### ISSUE THREAD

**Issue by aloysiustayy** [aaronlam2000/INF2001_P6-5#61]
High Priority

To further refine M1 Report section - Functional Requirements for Staff

Objective
- Draft and refine Functional Requirements for Staff (Pharmacist and Branch Staff)

Success Criteria
- Functional Requirements for Staff must be detailed and concise.
- The requirements fit the needs of the client.

Start Date: 7th September 2023
End Date: 11th September 2023
Allocated Time: 3 days

**Comment by poh-zun** [comment]
Drafting and refining of all functional requirements for staff completed.
There are a total of 7 requirements for staff: FR11 to FR17

Work was not committed to the repository.

Progress does not affect the deadline.

No changes to the criteria/success of the task.

Start Date: 7th September 2023
End Date: 11th September 2023
