### ISSUE TITLE
2.2.1 User Related Classes

### ISSUE THREAD

**Issue by Joo-ooo** [aaronlam2000/INF2001_P6-5#66]
High Priority

To create classes for classes related to users in the Class Diagram,

Objective

- Add in user related classes to the class diagram with their respective relationships

Success Criteria

- Create user entity class
- Create classes that inherit the user class
- Create control, boundary and interface classes related to users in the system.
- Define the relationships between the classes
- Include all necessary attributes and methods for each class.

Start Date: 25th September 2023
End Date: 20th October 2023
Allocated Time: 20 days

**Comment by aaronlam2000** [comment]
![Image](https://github.com/aaronlam2000/INF2001_P6-5/assets/32828969/1754aa4a-ab39-4115-9fa0-663e1fa4e354)

Completed user related classes and fulfilled success criteria.

Work was not committed to the repository.

Progress does not affect the deadline.

No changes to the criteria/success of the task.

Start Date: 25th September 2023
End Date: 20th October 2023
