### ISSUE TITLE
2.2.3 Preferences Related Classes

### ISSUE THREAD

**Issue by Joo-ooo** [aaronlam2000/INF2001_P6-5#68]
High Priority

To create classes for Preferences and related classes in Class Diagram

Objective

Complete diagram for Preferences and related classes
Success Criteria

Diagram for Preferences and related classes must have correct line type, arrow and relationships
Start Date: 25th September 2023
End Date: 20th October 2023
Allocated Time: 20 days

**Comment by aloysiustayy** [comment]
Entity, Control, Boundary classes done

**Comment by aloysiustayy** [comment]
Added interfaces after component diagram is done

**Comment by aloysiustayy** [comment]
Successfully created classes for Preferences and related classes in Class Diagram (Done by Aloysius).
Diagram created have correct line type (dotted or straight), arrow, and relationships


![Image](https://github.com/aaronlam2000/INF2001_P6-5/assets/105299134/1bb5f824-8780-4674-9d32-1ed7c5ace344)



Work was not committed to the repository.

Progress does not affect the deadline.

No changes to the criteria/success of the task.

Start Date: 25th September 2023
End Date: 20th October 2023
