### ISSUE TITLE
2.2.4 Workload Management Related Classes

### ISSUE THREAD

**Issue by Joo-ooo** [aaronlam2000/INF2001_P6-5#69]
Medium Priority

To complete the Class Diagram

Objective

- [x] #70 
- [x] #71 

Success Criteria

Classes must be clear and concise
Workload Management class diagram must cover all requirements needed

Start Date: 25th September 2023
End Date: 20th October 2023
Allocated Time: 20 Days

**Comment by sandracsm** [comment]
Completed all requirements for Workload Management Related Classes (Done by Poh Zun and Sandra)

Work was not committed to the repository.

Progress does not affect the deadline.

No changes to the criteria/success of the task.

Start Date: 25th September 2023
End Date: 20th October 2023
