### ISSUE TITLE
Finalise questions for Client Meeting 1

### ISSUE THREAD

**Issue by poh-zun** [aaronlam2000/INF2001_P6-5#7]
High Priority

To finalise questions to ask client during first client meeting

Objective

- Finalise a list of questions prepared to ask the client

Success Criteria

- Have a prepared list of questions to ask client during the first client meeting

Start Date: 4th September 2023
End Date: 4th September 2023
Allocated Time: 1 day

**Comment by aaronlam2000** [comment]
Finalised questions for client meeting 1:

**General Questions**

- How much access do each of them have?

- What should happen if a staff rejects the assigned job shift?

**Technical Questions**

- What information to use to visualize workload? (Hours? Time?)
- Is there a specific way you want us to visualize the workload? (graphs, tables, etc.)
(Recommendation - On Manager’s landing page, show top 3 staff with lowest workload for (upcoming week / month???)
- What details are needed when adding a new staff/manager to the system?

**Domain Specifics Questions**
- Is there a maximum working hours per week?

- Can you provide more details about the information to be displayed for each staff member, such as workload, preferences, and location at a particular date? How should this information be presented?
(Staff preferences should be which branch they want to go to? / timeslot)

- How do we define/measure workload (By amount of time, work etc)

- When do you need the product? Are there any hard deadlines to meet? 
- How long do you expect for the product to be delivered?

Start Date: 4th September 2023
End Date: 4th September 2023
