### ISSUE TITLE
2.2.4.1 View Workload Related Classes

### ISSUE THREAD

**Issue by Joo-ooo** [aaronlam2000/INF2001_P6-5#70]
High Priority

To complete M2 Report section - Class Diagram

Objective
- Draft and refine for View Workload Related Classes

Success Criteria
- The classes' attributes must be as detailed as possible.
- Relationship and mutiplicities stated in the diagram.

Start Date: 25th September 2023
End Date: 20th October 2023
Allocated Time: 20 days

**Comment by poh-zun** [comment]
![Image](https://github.com/aaronlam2000/INF2001_P6-5/assets/60766107/26eb4b87-e3b2-4301-978f-7f3983b2e416)

**Comment by poh-zun** [comment]
Drafting and refining of View Workload Related Classes completed
The classes are shown as above.

Work was not committed to the repository.

Progress does not affect the deadline.

No changes to the criteria/success of the task.

Start Date: 25th September 2023
End Date: 20th October 2023
