### ISSUE TITLE
2.2.4.2 Manage Workload Related Classes

### ISSUE THREAD

**Issue by Joo-ooo** [aaronlam2000/INF2001_P6-5#71]
High Priority

To complete M2 Report section - Class Diagram

Objective
- Draft and refine for Manage Workload Related Classes

Success Criteria
- The classes' attributes must be as detailed as possible.
- The classes must have the correct line type, arrow, and relationships

Start Date: 25th September 2023
End Date: 20th October 2023
Allocated Time: 20 days

**Comment by sandracsm** [comment]
![image](https://github.com/aaronlam2000/INF2001_P6-5/assets/107634194/bdde9943-3e40-4473-89c6-f5c5946d6e69)

**Comment by sandracsm** [comment]
Drafting and refining of Manage Workload Related Classes completed.
The classes are shown as above.

Work was not committed to the repository.

Progress does not affect the deadline.

No changes to the criteria/success of the task.

Start Date: 25th September 2023
End Date: 20th October 2023
