### ISSUE TITLE
2.3.1 User Management System

### ISSUE THREAD

**Issue by Joo-ooo** [aaronlam2000/INF2001_P6-5#72]
High Priority

To complete the User Management System component in the Component Diagram.

Objective

- Create User Management system component in the Component Diagram

Success Criteria

- Include Administrator, Manager, and Staff as sub-components within the User Management System.
- Delegate sub-components to appropriate ports for providing interfaces.

Start Date: 9th October 2023
End Date: 20th October 2023
Allocated Time: 10 days

**Comment by aaronlam2000** [comment]
![Image](https://github.com/aaronlam2000/INF2001_P6-5/assets/32828969/87a72dd3-59d9-4e1c-9bd3-10750599b557)



User Management System component in the Components Diagram has been completed as shown above.

Work was not committed to the repository.

Progress does not affect the deadline.

No changes to the criteria/success of the task.

Start Date: 9th October 2023
End Date: 20th October 2023
