### ISSUE TITLE
2.3.3 Preferences Manager

### ISSUE THREAD

**Issue by Joo-ooo** [aaronlam2000/INF2001_P6-5#74]
High Priority

To create component for Preferences Manager in Component Diagram

Objective

Complete diagram for Preferences Manager
Success Criteria

Diagram for Preferences Manager must have appropriate facet (providing interface) for other components to connect to
Start Date: 9th October 2023
End Date: 20th October 2023
Allocated Time: 10 days

**Comment by aloysiustayy** [comment]
Preference Manager component done and linked to port

**Comment by aloysiustayy** [comment]
Successfully created component diagram for Preferences Manager (Done by Aloysius).
Component created have appropriate facet (providing interface) 
![Image](https://github.com/aaronlam2000/INF2001_P6-5/assets/105299134/09ec8331-77ff-48bb-bb64-30ccaa61da48)

Work was not committed to the repository.

Progress does not affect the deadline.

No changes to the criteria/success of the task.

Start Date: 9th October 2023
End Date: 20th October 2023
