### ISSUE TITLE
2.3.4 Workload Management System

### ISSUE THREAD

**Issue by Joo-ooo** [aaronlam2000/INF2001_P6-5#75]
High Priority

To complete M2 Report section - Component Diagram

Objective

- Draft and refine for component diagram related to Workload Management System.

Success Criteria

- All the facets (lollipop) and connectors must shown correctly in the diagram
- List out all the components used for the system.

Start Date: 9th October 2023
End Date: 20th October 2023
Allocated Time: 10 days

**Comment by poh-zun** [comment]
![Image](https://github.com/aaronlam2000/INF2001_P6-5/assets/60766107/999572d2-04f6-446f-92c2-f27a72741587)

**Comment by poh-zun** [comment]
Drafting and refining of Workload Management System for Components Diagram completed.
The diagram are shown as above.

Work was not committed to the repository.

Progress does not affect the deadline.

No changes to the criteria/success of the task.

Start Date: 9th October 2023
End Date: 20th October 2023
