### ISSUE TITLE
2.3.5 Language Manager

### ISSUE THREAD

**Issue by Joo-ooo** [aaronlam2000/INF2001_P6-5#76]
High Priority

To complete M2 Report section - Component Diagram

Objective

Draft and refine for component diagram related to Language Manager.

Success Criteria

All the facets (lollipop) and connectors must shown correctly in the diagram
List out all the components used for the system.

Start Date: 9th October 2023
End Date: 20th October 2023
Allocated Time: 10 days

**Comment by Cherlin01** [comment]
![Image](https://github.com/aaronlam2000/INF2001_P6-5/assets/63331977/860a8e8b-4a78-4f7a-bedf-58880867d99e)

**Comment by Cherlin01** [comment]
Drafting and refining of Language Managment System for Components Diagram completed.
The diagram is shown as above.

Work was not committed to the repository.

Progress does not affect the deadline.

No changes to the criteria/success of the task.

Start Date: 9th October 2023
End Date: 20th October 2023
