### ISSUE TITLE
2.4.1 Job Allocation

### ISSUE THREAD

**Issue by Joo-ooo** [aaronlam2000/INF2001_P6-5#77]
High Priority

To complete M2 Report section - Sequence Diagram

Objective

Complete sequence diagram for Job Allocation based on the Use Case Description

Success Criteria

The diagram must follow the use case description
The diagram must describe how the objects communicate with each other
All flows must be shown in the diagram

Start Date: 23rd October 2023
End Date: 27th October 2023
Allocated Time: 5 days

**Comment by Cherlin01** [comment]
![Image](https://github.com/aaronlam2000/INF2001_P6-5/assets/63331977/a72a018e-f4cd-40b7-94b0-1939e64d5e8f)

**Comment by Cherlin01** [comment]
Creation of sequence diagram for Job Allocation completed.
The sequence diagram is shown as above.

Work was not committed to the repository.

Progress does not affect the deadline.

No changes to the criteria/success of the task.

Start Date: 23rd October 2023
End Date: 27th October 2023
