### ISSUE TITLE
2.4.2 View Employee Workload

### ISSUE THREAD

**Issue by Joo-ooo** [aaronlam2000/INF2001_P6-5#78]
High Priority

To complete M2 Report section - Sequence Diagram

Objective
- Complete sequence diagram for View Employee Workload based on the Use Case Description

Success Criteria
- The diagram must follow the use case description
- The diagram must describe how the objects communicate with each other
- All flows must be shown in the diagram

Start Date: 23rd October 2023
End Date: 27th October 2023
Allocated Time: 5 days

**Comment by sandracsm** [comment]
![image](https://github.com/aaronlam2000/INF2001_P6-5/assets/107634194/1d7de14d-d8ef-4002-9af9-d756e64d9ecd)

**Comment by sandracsm** [comment]
Creation of sequence diagram for View Employee Workload completed.
The sequence diagram is shown as above.

Work was not committed to the repository.

Progress does not affect the deadline.

No changes to the criteria/success of the task.

Start Date: 23rd October 2023
End Date: 27th October 2023
