### ISSUE TITLE
1.1.2 Product Scope

### ISSUE THREAD

**Issue by aaronlam2000** [aaronlam2000/INF2001_P6-5#8]
High Priority
To write up M1 Report section - Project Scope

Objective
- Draft out software product's scope
- Define the purpose of the product

Success Criteria
- Project Scope must be comprehensive and concise
- Project scope and purpose must be well defined

Start Date: 4th September 2023
End Date: 6th September 2023
Allocated Time: 3 days

**Comment by aloysiustayy** [comment]
Product scope drafted out in M1 Report document by Aaron

Work was not committed to the repository.

Progress does not affect the deadline.

No changes to the criteria/success of the task.

Start Date: 4th September 2023
End Date: 6th September 2023
