### ISSUE TITLE
3.2.2 Software Detailed Design

### ISSUE THREAD

**Issue by poh-zun** [aaronlam2000/INF2001_P6-5#81]
Medium Priority

To complete the Software Detailed Design

Objective

Implement two design patterns into existing class diagram

Success Criteria

Detailed Design must suit our application well.

Start Date: 30 October 2023
End Date: 10 November 2023
Allocated Time: 10 Days

**Comment by aloysiustayy** [comment]
Design pattern to use
1. Factory design pattern for Users (IT Admin, Manager, Staff)
2. Observer pattern for Preference-related classes

**Comment by aloysiustayy** [comment]
After consultation: 
1. Factory design pattern may not be as ideal
2. Look for new design pattern
3. Decided on Adapter pattern for Email service

**Comment by aloysiustayy** [comment]
1. Realised Observer pattern for Preference-related classes could be confusing. Thus changed to Job Allocation and iViewWorkload related classes
2. Observer pattern class diagram template taken from refactoring.guru website. 
3. Class diagram modified should match template **exactly**, did not know what is "Client", so changed template to geeksforgeeks


**refactoring.guru**
![Image](https://github.com/aaronlam2000/INF2001_P6-5/assets/105299134/eb6fe918-1c49-4c2d-9d3d-4a708ac0b95f)


**geeksforgeeks**

![Image](https://github.com/aaronlam2000/INF2001_P6-5/assets/105299134/a4d28afa-e5d2-4650-a54b-b6972bfd723a)

**Comment by aloysiustayy** [comment]
The Detailed Design suits our application well.
Ended with 
1. Abstract Pattern for email service
2. Observer Pattern for notifying Staffs for jobs assigned

Work was not committed to the repository.

Progress does not affect the deadline.

No changes to the criteria/success of the task.


Start Date: 30 October 2023
End Date: 10 November 2023
