### ISSUE TITLE
3.3 Testing

### ISSUE THREAD

**Issue by poh-zun** [aaronlam2000/INF2001_P6-5#82]
Medium Priority

To do Black-Box and White-Box Testing

Objective

- [x] #83 
- [x] #84 

Success Criteria

The Application meets the requirement and specifications
The Application is user-friendly

Start Date: 30 October 2023
End Date: 22 November 2023
Allocated Time: 18 Days

**Comment by aaronlam2000** [comment]
Completed Black-Box and White-Box testing objectives.
Ensured all success criteria has been met.

Work was not committed to the repository.

Progress does not affect the deadline.

No changes to the criteria/success of the task.

Start Date: 30 October 2023
End Date: 22 November 2023
