### ISSUE TITLE
3.3.1 Black Box Testing

### ISSUE THREAD

**Issue by poh-zun** [aaronlam2000/INF2001_P6-5#83]
Medium Priority

To do Black-Box Testing

Objective

Complete Black-Box Testing

Success Criteria

The Application meets the requirement and specifications
The Application is user-friendly

Start Date: 30 October 2023
End Date: 10 November 2023
Allocated Time: 11 Days

**Comment by Joo-ooo** [comment]
Completed Black-box testing

First Iteration of Decision Table

![Image](https://github.com/aaronlam2000/INF2001_P6-5/assets/113295507/077a29c6-5a15-450d-b0b1-cc8adb06397f)


Reduced Decision Table

![Image](https://github.com/aaronlam2000/INF2001_P6-5/assets/113295507/8af6cda6-7e15-43ed-80b4-882698775c5f)


Test Case Table

![Image](https://github.com/aaronlam2000/INF2001_P6-5/assets/113295507/c1c52e91-4d64-4944-b00e-9f228d0bb836)


Work was not committed to the repository.

Progress does not affect the deadline.

No changes to the criteria/success of the task.

Start Date: 30 October 2023
End Date: 10 November 2023
