### ISSUE TITLE
3.3.2 White Box Testing

### ISSUE THREAD

**Issue by poh-zun** [aaronlam2000/INF2001_P6-5#84]
Medium Priority

To do White-Box Testing

Objective
Write Pseudo code for a prominent method
Perform White-Box testing on the method by constructing Control Flow Graph (CFG)
Calculate cyclomatic complexity and identify basis paths
Create testcases for basis paths

Success Criteria
Pseudo code is complete with no logical errors
Completed CFG and identified correct basis paths
All calculations are accurate
All basis paths has a test case

The Application meets the requirement and specifications
The code is optimized
All bugs are discovered and fixed

Start Date: 13 November 2023
End Date: 22 November 2023
Allocated Time: 9 Days

**Comment by aaronlam2000** [comment]
Implemented updateAssignments() pseudo code
![image](https://github.com/aaronlam2000/INF2001_P6-5/assets/32828969/45840aec-d558-4189-b606-14aaa094274c)

**Comment by aaronlam2000** [comment]
Constructed CFG for the function, calculated cyclomatic complexity and identified 4 basis paths.

Cyclomatic Complexity (M) = 16 - 14 + 2(1) = 4

Basis Paths:
1) 1, 2, 3, 4, 5, 9, 3, 10, 12, 13, 14
2) 1, 2, 3, 4, 5, 9, 3, 10, 11, 14
3) 1, 2, 3, 4, 5, 6, 7, 8, 10, 11, 12, 13, 14
4) 1, 2, 3, 10, 11, 14

![image](https://github.com/aaronlam2000/INF2001_P6-5/assets/32828969/79073a58-5e5d-4e6f-a99d-6ed32a4cfc7e)

**Comment by aaronlam2000** [comment]
Completed test cases for each basis path:
![image](https://github.com/aaronlam2000/INF2001_P6-5/assets/32828969/917f5263-34e3-45cb-a312-6b89087ed676)

**Comment by aaronlam2000** [comment]
Completed all the objectives of White-Box Testing
Pseudo code is free of logical errors
Created CFG and ensure accurate calculations of cyclomatic complexity
Identified all the basis paths accurately
Create test cases for all the required basis paths

Work was not committed to the repository.

Progress does not affect the deadline.

No changes to the criteria/success of the task.

Start Date: 13 November 2023
End Date: 22 November 2023
