### ISSUE TITLE
3.4 Prototypes & Wireframes

### ISSUE THREAD

**Issue by poh-zun** [aaronlam2000/INF2001_P6-5#85]
Medium Priority

To do Wireframe

Objective

- [x] #86 
- [x] #87 
- [x] #88 

Success Criteria

The Wireframe implements all use cases in use case description.
The Wireframe fulfils all functional requirements (FR) and user interface requirements (UIR)

Start Date: 13 November 2023
End Date: 24 November 2023
Allocated Time: 10 Days

**Comment by sandracsm** [comment]
Creation of wireframes for staffs completed.
The wireframes are shown in #87 .

Work was not committed to the repository.

Progress does not affect the deadline.

No changes to the criteria/success of the task.

Start Date: 13 November 2023
End Date: 24 November 2023

**Comment by Cherlin01** [comment]
Creation of wireframes for Managers and Administrator completed.
The wireframes are shown in #86 and #88 

Work was not committed to the repository.

Progress does not affect the deadline.

No changes to the criteria/success of the task.

Start Date: 13 November 2023
End Date: 24 November 2023
