### ISSUE TITLE
3.4.1 Wireframes for Manager

### ISSUE THREAD

**Issue by poh-zun** [aaronlam2000/INF2001_P6-5#86]
Medium Priority

To do Manager Wireframe

Objective

Complete Wireframe for Manager

Success Criteria

The Wireframe implements all of Manager use cases in use case description.
The Wireframe fulfils all functional requirements (FR) and user interface requirements (UIR) of Manager

Start Date: 13 November 2023
End Date: 24 November 2023
Allocated Time: 10 Days

**Comment by Cherlin01** [comment]
Manager Home Page

![Image](https://github.com/aaronlam2000/INF2001_P6-5/assets/63331977/10d467ae-bc80-4697-929d-14f1af6b40d6)

Manager Job Allocation Page

![Image](https://github.com/aaronlam2000/INF2001_P6-5/assets/63331977/d8068939-c8b8-4e67-a76a-0d1e0474f7d5)

Manager View Employees Page

![Image](https://github.com/aaronlam2000/INF2001_P6-5/assets/63331977/cca18490-8b53-432f-9659-4641a48d0504)

Manager View Preference Page

![Image](https://github.com/aaronlam2000/INF2001_P6-5/assets/63331977/b7c547ac-4357-4141-8c3b-d05c3a5df629)

Manager Download Popup Page

![Image](https://github.com/aaronlam2000/INF2001_P6-5/assets/63331977/4c82ed86-8db7-4bdd-aaa9-2ba2e208cbd7)

Manager Edit Employee Details Page

![Image](https://github.com/aaronlam2000/INF2001_P6-5/assets/63331977/917f9c96-2497-4a9c-bd2e-296d0258c4a3)

Manager Account Settings Page

![Image](https://github.com/aaronlam2000/INF2001_P6-5/assets/63331977/c866e335-c9c8-40b5-a4a4-84c3cc74118f)

**Comment by Cherlin01** [comment]
Creation of Wireframes for Manager completed.
The wireframes are shown as above.

Work was not committed to the repository.

Progress does not affect the deadline.

No changes to the criteria/success of the task.

Start Date: 13 November 2023
End Date: 24 November 2023
