### ISSUE TITLE
3.4.2 Wireframes for Staffs

### ISSUE THREAD

**Issue by poh-zun** [aaronlam2000/INF2001_P6-5#87]
Medium Priority

To do Staff Wireframe

Objective

Complete Wireframe for Staff

Success Criteria

The Wireframe implements all of Staff use cases in use case description.
The Wireframe fulfils all functional requirements (FR) and user interface requirements (UIR) of Staff

Start Date: 13 November 2023
End Date: 24 November 2023
Allocated Time: 10 Days

**Comment by sandracsm** [comment]
Settings page for Staff
![image](https://github.com/aaronlam2000/INF2001_P6-5/assets/107634194/d43de2fd-216f-45c7-968d-925628325f02)

Landing page for Staff
![image](https://github.com/aaronlam2000/INF2001_P6-5/assets/107634194/62ce1ed0-3b63-4735-936e-c89c65a4e43a)

Job Details Pop-up Box
![image](https://github.com/aaronlam2000/INF2001_P6-5/assets/107634194/a0a065d4-f7a4-4a46-bfd7-86c6a0bf541a)

Edit Job Availability & Preferences Page and Pop-up Box
![image](https://github.com/aaronlam2000/INF2001_P6-5/assets/107634194/ce875b57-5856-4abb-8768-3526592c3873)
![image](https://github.com/aaronlam2000/INF2001_P6-5/assets/107634194/4b3a605a-265a-4a60-916e-e0270720f6a0)

View Assigned and Rejected Job
![image](https://github.com/aaronlam2000/INF2001_P6-5/assets/107634194/fe4e9f2b-e100-402f-8b9d-f43c54144449)
Warning Pop-up
![image](https://github.com/aaronlam2000/INF2001_P6-5/assets/107634194/d9168bd8-18a3-4f56-9dab-59bd30de6adc)

**Comment by sandracsm** [comment]
Creation of wireframes for staffs completed.
The wireframes are shown as above.

Work was not committed to the repository.

Progress does not affect the deadline.

No changes to the criteria/success of the task.

Start Date: 13 November 2023
End Date: 24 November 2023
