### ISSUE TITLE
3.4.3 Wireframes for Administrators

### ISSUE THREAD

**Issue by poh-zun** [aaronlam2000/INF2001_P6-5#88]
Medium Priority

To do Administrator Wireframe

Objective

Complete Wireframe for Administrator

Success Criteria

The Wireframe implements all of Administrator use cases in use case description.
The Wireframe fulfils all functional requirements (FR) and user interface requirements (UIR) of Administrator

Start Date: 13 November 2023
End Date: 24 November 2023
Allocated Time: 10 Days

**Comment by Cherlin01** [comment]
Administrator View Employee Page

![Image](https://github.com/aaronlam2000/INF2001_P6-5/assets/63331977/d0fb7072-a14b-44fe-a110-f7e703649513)

Administrator Delete Warning Box Page

![Image](https://github.com/aaronlam2000/INF2001_P6-5/assets/63331977/f9fa6431-85c0-4020-bc1d-302b424a4162)

Administrator Reset Password Warning Box Page

![Image](https://github.com/aaronlam2000/INF2001_P6-5/assets/63331977/26b5f0f2-6d7d-4b6a-9e45-8b7d63554428)

Administrator Create Account Page

![Image](https://github.com/aaronlam2000/INF2001_P6-5/assets/63331977/98ac9bf0-d115-458e-82f0-cd3f5a156c78)

Administrator Edit Employee Details Page

![Image](https://github.com/aaronlam2000/INF2001_P6-5/assets/63331977/78c8a544-725c-4987-98c4-6fe84e2f4706)

Administrator View Role List Page

![Image](https://github.com/aaronlam2000/INF2001_P6-5/assets/63331977/f289678f-1d0a-4f74-8c69-e845a53b0693)

Administrator Edit Role Permission Page

![Image](https://github.com/aaronlam2000/INF2001_P6-5/assets/63331977/e394b152-e2da-47d1-9ed6-12bff00e639b)

**Comment by Cherlin01** [comment]
Creation of Wireframes for Administrator completed.
The wireframes are shown as above.

Work was not committed to the repository.

Progress does not affect the deadline.

No changes to the criteria/success of the task.

Start Date: 13 November 2023
End Date: 24 November 2023
