### ISSUE TITLE
Research on existing staff management systems

### ISSUE THREAD

**Issue by aaronlam2000** [aaronlam2000/INF2001_P6-5#9]
Medium Priority

To do research on existing Staff Management Systems

Objective

- Research on existing tools related to our product
- Research on related topics to our product's domain

Success Criteria

- Complete the following objectives stated above

Start Date: 6th September 2023
End Date: 10th September 2023
Allocated Time: 5 days

**Comment by aloysiustayy** [comment]
Discover.quickhr.co
Track tasks assigned to specific employees

**Comment by Joo-ooo** [comment]
Researched on existing staff management software such as QuickHR, When I Work and Deputy on their functional requirements such as employee scheduling software, time sheet and attendance tracking. Non-functional requirements such as leveraging AWS security, audit trail and security and allowing many users to access the application at the same time.

Work was not committed to repo.

No changes to criteria/success

Start Date: 6th September 2023
End Date: 17th September 2023
